[package]
name = "Amalgam"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = 0.13.0
tokio = { version = "1.25.0", features = ["full"] }